<?php
/**
 * Visualizar feed RSS por Joanhey
 *
 * @param string $nombre Nombre
 * @param string $url URL completa del feed
 * @return html
 */

if ($feed = simplexml_load_file($url)): ?>
    <div class="feed">
    <h3><a href="<?php echo h($feed->channel->link)?>" title="<?php echo h($feed->channel->description)?>"><?php echo h($name)?></a></h3>
    <ul>
    <? foreach ($feed->channel->item as $item) : ?>
    <li><a href="<?php echo h($item->link)?>" title="<?php echo h(substr(strip_tags($item->description),0,200))?>..."><?php echo h($item->title)?></a></li>
    <? endforeach?>
</ul></div>
<?php endif?>
