<?php
/**
 * Visualizar feed por Joanhey
 *
 * @param string $nombre Nombre
 * @param string $url URL completa del feed
 * @return html
 */

if ($feed = simplexml_load_file($url)): ?>
    <div class="feed">
    <h3><a href="<?=$feed->channel->link?>" title="<?= h($feed->channel->description)?>"><?= $name?></a></h3>
    <ul>
    <? foreach ($feed->channel->item as $item) : ?>
    <li><a href="<?= $item->link?>" title="<?= $item->description?>"><?=$item->title?></a></li>
    <? endforeach?>
</ul></div>
<?php endif?>
