<div id="social" class="span6">
	<p>¡Compártelo!</p>
	<?php $url = "https://$_SERVER[SERVER_NAME]$_SERVER[REQUEST_URI]";
    $titulo = View::getVar('page_title'); ?>
    <a class="social facebook" rel="nofollow noopener" href="https://www.facebook.com/share.php?u=<?= $url; ?>&t=<?= urlencode($titulo); ?>" title="Facebook" target="_blank"></a>
	<a class="social twitter" rel="nofollow noopener" href="https://twitter.com/intent/tweet?text=<?= urlencode($titulo); ?>&url=<?=$url; ?>&via=KumbiaPHP" title="Twitter" target="_blank"></a>
	<a class="social google" rel="nofollow noopener" href="https://plusone.google.com/_/+1/confirm?hl=es&url=<?= $url; ?>" title="Google +1" target="_blank"></a>
</div>