<header class="container-top">    
    <div class="row">
        <h1>Escaparate Web</h1>
        <p>Conoce webs hechas con KumbiaPHP.</p>
    </div>
</header>

<div class="row">
    <div class="row">            
        <div class="span3">
            <?php View::partial('escaparate/categorias') ?>
        </div>
        <div class="span9">
            <div class="tab-content">
                <div class="tab-pane active" id="lA">
                    <div class="row-fluid">
                        <ul class="thumbnails">
                            <?php include 'items.phtml'; ?>
                        </ul>
                    </div>
                </div>
                <!--                <div class="tab-pane" id="lB">
                                    <p>Howdy, I'm in Section B.</p>
                                </div>
                                <div class="tab-pane" id="lC">
                                    <p>What up girl, this is Section C.</p>
                                </div>-->
            </div>
        </div>                
    </div>	
</div>
</div>
