<header>    
    <div class="row container-top">
        <h1>Escaparate Web</h1>
        <p>Conoce webs hechas con KumbiaPHP.</p>
    </div>
</header>

<div class="row">
        <div class="row">            
            <div class="span3">
                <ul class="nav nav-tabs">	
                    <li class="active"><a href="#lA" data-toggle="tab">CMS </a></li>
                    <li class=""><a href="#lB" data-toggle="tab">Personal</a></li>
                    <li class=""><a href="#lC" data-toggle="tab">Educacion</a></li>
                </ul>
            </div>
            <div class="span9">
                <div class="tab-content">
                    <div class="tab-pane active" id="lA">
                        <div class="row-fluid">
                            <ul class="thumbnails">
                                <li class="span3">
                                    <div class="thumbnail">
                                        <img src="http://placehold.it/215x161" alt="">
                                        <div class="caption">
                                            <h3>Thumbnail label</h3>
                                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                            <p><span class="label">cms</span> <span class="label">tecnologia</span></p>
                                        </div>
                                    </div>
                                </li>
                                <li class="span3">
                                    <div class="thumbnail">
                                        <img src="http://placehold.it/215x161" alt="">
                                        <div class="caption">
                                            <h3>Thumbnail label</h3>
                                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                            <p><span class="label">cms</span> <span class="label">tecnologia</span></p>
                                        </div>
                                    </div>
                                </li>
                                <li class="span3">
                                    <div class="thumbnail">
                                        <img src="http://placehold.it/215x161" alt="">
                                        <div class="caption">
                                            <h3>Thumbnail label</h3>
                                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                            <p><span class="label">cms</span> <span class="label">tecnologia</span></p>
                                        </div>
                                    </div>
                                </li>
                                <li class="span3">
                                    <div class="thumbnail">
                                        <img src="http://placehold.it/215x161" alt="">
                                        <div class="caption">
                                            <h3>Thumbnail label</h3>
                                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                            <p><span class="label">cms</span> <span class="label">tecnologia</span></p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="tab-pane" id="lB">
                        <p>Howdy, I'm in Section B.</p>
                    </div>
                    <div class="tab-pane" id="lC">
                        <p>What up girl, this is Section C.</p>
                    </div>
                </div>
            </div>                
        </div>	
    </div>
</div>
