<header>    
    <div class="row container-top page-header">
        <h1>Características de KumbiaPHP Framework</h1>
        <p>KumbiaPHP Framework es muy flexible y configurable, que facilita construir aplicaciones 
            robustas, para entornos comerciales.</p>
    </div>    
</header>

<div class="row">
    <div class="span3">
        <div class="leftContent ico_modelo">
        <h3>Modelo de objectos y MVC</h3>
        <p>KumbiaPHP se basa en el patrón de diseño <abbr title="Modelo Vista Controlador">MVC</abbr>, bajo una capa de abstracción a base de datos que simplifica la programación y mejora el mantenimiento de la aplicación.</p>	
        </div>
    </div>
    <div class="span3">
        <div class="leftContent ico_soporte">
        <h3>Soporte de plantillas</h3>
        <p>Usando tres niveles de vistas, KumbiaPHP permite generar sitios web rápidamente, permitiendo definir templates y partials ajustados a cada acción.</p>	
        </div>
    </div>
    <div class="span3">
        <div class="leftContent ico_scaffold">
        <h3>Scaffolding Avanzado</h3>
        <p>¿Necesitas empezar por algo práctico? KumbiaPHP te ayuda a crear un andamiaje sencillo y básico para empezar a utilizarlo.  Solo tienes que indicar las acciones que tiene que hacer y el resto lo hará por ti. </p>
        </div>			
    </div>		
    <div class="span3">
        <div class="leftContent ico_cache">
        <h3>Administración de Cache</h3>
        <p>Una vez tu aplicativo lo configuras en modo de producción, podrás generar un caché de archivos y base de datos, para mejorar la carga de tu sitio web.</p>
        </div>
    </div>
</div>
    
<div class="row">
    <div class="span3">
        <div class="leftContent ico_soporte2">
        <h3>Soporte para AJAX</h3>
        <p>KumbiaPHP dispone de librerías adaptadas para usar <abbr title="Asynchronous JavaScript And XML - JavaScript asíncrono y XML">AJAX</abbr>, pero también puedes combinarlo fácilmente, con librería externas tales como Scriptacoulous, ExtJS, entre otros.</p>
        </div>
    </div>
    <div class="span3">
        <div class="leftContent ico_form">
        <h3>Autocarga de objetos</h3>
        <p>Como su nombre lo indica y siguiendo una convención simple en tus formularios, KumbiaPHP asocia los datos enviados (mediante el método POST) con los de una tabla y campo de la BD, generando ahorros de tiempo y trabajo en tus apliaciones.</p>
        </div>
    </div>
    <div class="span3">
        <div class="leftContent ico_image">
        <h3>Componentes Gráficos</h3>
        <p>Porque no todo es programación, KumbiaPHP es extensible y compatible con la mayoría de herramientas gráficas y de animaciones como JQuery UI, Bootstrap de Twitter y Mootools entre otros.</p>		
        </div>
    </div>
    <div class="span3">
        <div class="leftContent ico_seguridad">
        <h3>Seguridad</h3>
        <p>Para nuestro equipo la seguridad es muy importante, por eso nuestro framework incluye sistemas de verificación, validación y filtros de datos de entrada, prevención a la inyección SQL y muchos más opciones para evitar intrusiones no deseadas en tus aplicaciones web.</p>
        </div>		
    </div>
</div>
