<div class="container-fluid container-top">    
    <div class="page-header span6">        
        <h1>Descargas KumbiaPHP Framework</h1>
        <p>KumbiaPHP Framework PHP intenta proporcionar facilidades para construir aplicaciones 
            robustas para entornos comerciales. Esto significa que el framework es muy flexible y configurable.</p>
    </div>    
</div>

<div class="container-fluid container-bottom">
    <div class="row-fluid">
        <div class="span6">
            <div class="download-package">
                <h2>KumbiaPHP - Spirit</h2>
                <ul class="download-list">
                    <li><span class="download-name">Spirit 1.0 - Beta2</span><span class="download-action"><a href=""><i class="icon icon-download"></i> Descargar</a></span></li>
                    <li><span class="download-name">Spirit 1.0 - Beta1</span><span class="download-action"><a href=""><i class="icon icon-download"></i> Descargar</a></span></li>
                </ul>		
            </div>
            <div class="clearfix"><!-- BR --></div>
            <div class="download-package">
                <h2>KumbiaPHP - 0.5</h2>
                <ul class="download-list">
                    <li><span class="download-name">KumbiaPHP 0.5 - Estable</span><span class="download-action"><a href=""><i class="icon icon-download"></i> Descargar</a></span></li>
                </ul>
            </div>
            <div class="download-package">
                <h2>KumbiaPHP - 0.4</h2>
                <ul class="download-list">
                    <li><span class="download-name">KumbiaPHP 0.4.7 - Estable</span><span class="download-action"><a href=""><i class="icon icon-download"></i> Descargar</a></span></li>
                </ul>
            </div>			
        </div>
        <div class="span6">
            <h2>Requisitos</h2>
        </div>
    </div>
</div>