<header>    
    <div class="row container-top">        
        <h1>Descargar KumbiaPHP Framework</h1>
        <p>¡Bájate KumbiaPHP framework y empieza a probarlo!</p>
    </div>    
</header>

<div class="row">
    <div class="span6">
    <h2>Descargas</h2>
    <a href="#" class="btn-large" title="Descarga la última versión de KumbiaPHP">Descargar KumbiaPHP 1.0</a>
    </div>
    <div class="span6">
        <h2>Requisitos</h2>
        <ul>
            <li><strong>PHP</strong> 5.4+</li>
            <li><strong>mod_rewrite</strong> en Apache (o similar para otros servidores)</li>
            <li><strong>Servidor web</strong> (probado en Apache, Nginx, IIS, Cherookee)</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="span6">
    <h4>Versiones antiguas</h4>
    <p>Por si tienes nostalgia, o necesitas una copia. Recuerda que estas versiones tienen otros requisitos.</p>
    <ul class="download-list">
        <li><a href="#" class="download-name">Spirit 1.0 - Beta2</a></li>
        <li><a href="#" class="download-name">Spirit 1.0 - Beta1</a></li>
        <li><a href="#" class="download-name">KumbiaPHP 0.5</a></li>
        <li><a href="#" class="download-name">KumbiaPHP 0.4.7</a></li>
    </ul>
    </div>
</div>
