<div id="slogan-home" class="slogan">
	<div class="container">
		<div class="span5">
			<h1>KumbiaPHP Framework</h1>
			<h2>Programar puede ser más fácil.</h2>
			<p>Descarga KumbiaPHP y desarrolla aplicaciones web estables y rápidas.</p>
			<?php echo Html::link('#','Descargar Spirit 1b2','class="btn btn-large btn-warning"')?>
		</div>
		<div class="span5"><?php echo Html::img('inicio-kumbiaphp.png','','width=350px') ?></div>
	</div>
</div>
<div class="container">
	<div id="features" class="row">
		<div class="span4">
			<h3>Rápido, ligero y flexible</h3>
			<p>KumbiaPHP es un framework para aplicaciones web libre escrito en PHP5. Basado en las prácticas de desarrollo web como DRY y el Principio KISS para software comercial y educativo. Kumbiaphp fomenta la velocidad y eficiencia en la creación y mantenimiento de aplicaciones web, reemplazando tareas de codificación repetitivas por poder, control y placer.</p>  
			<p><?php echo Html::link('','Leer más')?></p>	
			<?php echo Html::img('rapido.png') ?>
		</div>
		<div class="span4">
			<h3>Documentación en español</h3>
			<p>Aprende y disfruta de KumbiaPHP con los múltiples tutoriales y documentación en español que hay disponible a traves de la wiki y del API.</p>
			<p>Lee más sobre la <?php echo Html::link('','documentación en español')?>.</p>
			<?php echo Html::img('doc.png') ?>
		</div>
		<div class="span4">
			<h3>Repositorio GitHub</h3>
			<p>Puedes descargar la última versión en desarrollo en GITHub y disponer de las últimas correcciones, cambios y mejoras..</p>
			<p>			<?php echo Html::img('github-img.jpeg') ?>
<?php echo Html::link('','KumbiaPHP en GitHub')?></p>
		</div>
	</div>
</div>