<div class="container-fluid container-top">    
    <div class="page-header span6">
        <h1>IRC Chat</h1>
        <p>Conoce a través de nuestro IRC a más kumbieros como tú..</p>
    </div>    
</div>

<div class="container-fluid container-bottom">
    <div class="row-fluid">
        <div class="span12">
            <iframe src="http://webchat.freenode.net?nick=kumbiero....&channels=kumbiaphp&prompt=1&uio=MTE9MA4c" width="100%" height="400"></iframe>
        </div>
    </div>
</div>