<article>
    <header>
        <h1><?=$title = $post->post_title; ?></h1>
        <div class="meta-data">
        <span>
            <svg style="width:20px;height:20px" viewBox="0 0 24 24">
            <path fill="#888" d="M9,10H7V12H9V10M13,10H11V12H13V10M17,10H15V12H17V10M19,3H18V1H16V3H8V1H6V3H5C3.89,3 3,3.9 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5A2,2 0 0,0 19,3M19,19H5V8H19V19Z" />
            </svg>
            <?=$post->post_date; ?>
        </span>
        <span>
            <?=Html::gravatar($post->user_email, 'gravatar', 30); ?>  by 
            <a href="/blog/author/<?=$post->user_nicename; ?>/"><?=$post->display_name; ?></a>
        </span>
        <span>
            <svg style="width:20px;height:20px" viewBox="0 0 24 24">
            <path fill="#888" d="M9,22A1,1 0 0,1 8,21V18H4A2,2 0 0,1 2,16V4C2,2.89 2.9,2 4,2H20A2,2 0 0,1 22,4V16A2,2 0 0,1 20,18H13.9L10.2,21.71C10,21.9 9.75,22 9.5,22V22H9M10,16V19.08L13.08,16H20V4H4V16H10M6,7H18V9H6V7M6,11H15V13H6V11Z" />
            </svg> 
            <a href="#comments">
                <?=$post->comment_count; ?> Comentarios
            </a>
        </span>
        <span class="u-pull-right">
            <a href="//www.facebook.com/sharer/sharer.php?u=https://<?=$_SERVER['SERVER_NAME'], $_SERVER['REQUEST_URI']; ?>"
                rel="nofollow noopener" target="_blank"><img src="/img/icon-facebook.svg" width="30"></a>  
            <a href="//twitter.com/home?status=https://<?=$_SERVER['SERVER_NAME'], $_SERVER['REQUEST_URI']; ?>"
                rel="nofollow noopener" target="_blank"><img src="/img/icon-twitter.svg" width="30"></a>
        </span>
        </div>
    </header>
        <div><?= _wp::more($post->post_content); ?></div>
        <div>
            <?php foreach ($tags as $tag) : ?>
                <a href="/blog/tag/<?=$tag->slug; ?>/">
                    <span class="chip"><?=$tag->name; ?></span>
                </a>
            <?php endforeach; ?>
        </div>
</article>
<section id="comments">
    <?php if ($comments) {
    echo var_dump($comments);
} //WpComments::all($comments)?>
    <div class="collection">
        <div class="collection-item grey lighten-5 mt15" id="formulario">
            <h4>Deja un comentario</h4>
            <form action method="post">
                <p>
                    <em><small>Tu dirección de correo electrónico no será publicada. Los campos obligatorios están marcados con *</small></em>
                </p>
                <?php if (Input::get('responder') and $comment) : ?>
                    <p>
                        Estas contestando a <?=$comment->comment_author; ?>
                        <blockquote><?=$comment->comment_content; ?></blockquote>
                        <input type="hidden" name="parent" value="<?=$comment->comment_ID; ?>">
                    </p>
                <?php else : ?>
                    <input type="hidden" name="parent" value="0">
                <?php endif; ?>
                <p>
                    <label for="comment">Comentario *</label> 
                    <textarea id="comment" name="comment" maxlength="65525" required><?=(Input::get('editar') and $comment) ? $comment->comment_content : ''; ?></textarea>
                </p>
                <p>
                    <label for="author">Nombre o alias *</label>
                    <input type="text" id="author" name="author" maxlength="245" required value="<?=(Input::get('editar') and $comment) ? $comment->comment_author : ''; ?>">
                </p>
                <p>
                    <label for="email">Correo electrónico *</label>
                    <input type="email" id="email" name="email" maxlength="100" value="<?=(Input::get('editar') and $comment) ? $comment->comment_author_email : ''; ?>">
                </p>
                <p>
                    <label for="url">Web</label>
                    <input type="url" id="url" name="url" maxlength="200" value="<?=(Input::get('editar') and $comment) ? $comment->comment_author_url : ''; ?>">
                </p>
                <p class="hide">
                    <label for="telefono">Telefono</label>
                    <input type="text" id="telefono" name="telefono" maxlength="9">
                </p>
                <p>
                    <?php if (Input::get('editar') and $comment) : ?>
                        <button type="submit" class="btn orange darken-1" name="edit_comment" value="<?=$comment->comment_ID; ?>">Actualizar</button> 
                        <button type="submit" class="btn red darken-1" name="quit_comment" value="<?=$comment->comment_ID; ?>">Eliminar</button> 
                    <?php else : ?>
                        <button type="submit" class="button button-primary" name="add_comment" value="1">Publicar comentario</button> 
                    <?php endif; ?>
                    <input type="hidden" name="post_ID" value="<?=$post->ID; ?>">
                </p>            
            </form>
        </div>   
    </div>
</section> 