<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8"/>
<?php if (! isset($title)) : ?>
<title>KumbiaPHP web &amp; app Framework</title>
<?php else : ?>
<title><?php echo $title ?> - KumbiaPHP</title>
<?php endif ?>
<!--<link rel="stylesheet" href="/css/bootstrap.css"/>
<link rel="stylesheet" href="/css/structure.css"/>
<link rel="stylesheet" href="/css/style.css"/>-->
<?php Tag::css('bootstrap') ?>
<?php Tag::css('structure') ?>
<?php Tag::css('style') ?>
<?php echo Html::includeCss() ?>

</head>
<body>

	<?php View::partial('main/navbar') ?>
	
	<div id="content">
	<?php View::content() ?>
	</div>
		
	<?php View::partial('main/footer') ?>                

<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "e05a5a49-dee3-49a4-9cf0-5333a28fa9a5"}); </script>
<?php echo Tag::js('jquery/jquery.min') ?> 
<?php echo Tag::js('bootstrap/bootstrap') ?>
</body>
</html><?= '<!-- Tiempo: ' . round(microtime(1) - START_TIME, 4) . ' seg. -->'?>