<footer>
    <div class="row">
            <div class="span5">
                <p>Web creada con KumbiaPHP usando <?php echo Html::img('HTML5.png','HTML5')?></p>
            </div>
            <div class="span7" style="text-align: right">
                <span class="st_sharethis_hcount social-hub"></span>
                <span class="st_facebook_hcount social-hub"></span>
                <span class="st_twitter_hcount social-hub"></span>
                <span class="st_googleplus_hcount social-hub"></span>
            </div>
    </div>
</footer>