<div id="footer" class="navbar navbar-fixed-bottom">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span5">
                <p>Esta web está creada con Kumbiaphp</p>                        
            </div>
            <div class="span7" style="text-align: right">					                            
                <span class="st_sharethis_hcount social-hub" displayText="ShareThis"></span>
                <span class="st_facebook_hcount social-hub" displayText="Facebook"></span>
                <span class="st_twitter_hcount social-hub" displayText="Tweet"></span>
                <span class="st_googleplus_hcount social-hub" displayText="Google +"></span>                            
            </div>
        </div>	
    </div>
</div>