<nav>
<div class="row">
    <?php echo Html::link('','KumbiaPHP','class="logo span3" title="KumbiaPHP Framework PHP MVC"');//Html::img('kumbiaphp.png','KumbiaPHP Framework','width=183 height=50')) ?> 
    <ul class="menu">
        <li><?php echo Html::link('caracteristicas/', 'Características') ?></li>
        <li><?php echo Html::link('escaparate/', 'Escaparate') ?></li>
        <li><a href="http://www.kumbiaphp.com/blog/">Blog</a><?php //echo Html::link('blog/', 'Blog') ?></li>
        <li><?php echo Html::link('aprender/', 'Documentación') ?></li>
        <li><?php echo Html::link('comunidad/', 'Comunidad') ?></li>
        <li><?php echo Html::link('descargas/', 'Descargar') ?></li>
    </ul>
</div>
</nav>