<nav>
<div class="row">
    <a href="/" class="span3 logo" title="KumbiaPHP Framework PHP MVC"><img src="/img/kumbiaphp.svg" alt="KumbiaPHP Framework" width="259" height="30"/></a>     
    <div class="span9">
    <label for="off-canvas">≡ Menu</label>
    <input type="checkbox" id="off-canvas">
    <ul class="menu <?= $menu; ?>">
        <li><a href="/caracteristicas/" class="caracteristicas">Características</a></li>
        <li><a href="/escaparate/" class="escaparate">Escaparate</a></li>
        <li><a href="/blog/" class="blog">Blog</a></li>
        <li><a href="/aprender/" class="aprender">Documentación</a></li>
        <li><a href="/comunidad/" class="comunidad">Comunidad</a></li>
        <li><a href="/descargas/" class="descargas">Descargar</a></li>
    </ul>
    </div>
</div>
</nav> 